sohpen/sohpen/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls', namespace='website')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sohpen/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^testfront/$', TestFrontend.as_view(), name="test"),
    url(r'^$', HomeView.as_view(), name="home"),


    url(r'^sophenAdmin/$', Dashboard.as_view(), name="dashboard_main"),
    url(r'^sophenAdmin/dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^sophenAdmin/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^sophenAdmin/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),
    url(r'^sophenAdmin/password-change/$',
        ChangePasswordView.as_view(), name='changePassword'),

    url(r'^sophenAdmin/page/list/$',
        PageListView.as_view(), name='pageList'),
    url(r'^sophenAdmin/conferenceMembership/list/$',
        ConferenceMemberListView.as_view(), name='confList'),
    url(r'^sophenAdmin/conferenceMembershipDetail/(?P<pk>[\d]+)$',
        ConferenceRegistrationDetailView.as_view(), name='confDetail'),
    url(r'^sophenAdmin/page/create/$',
        PageCreateView.as_view(), name='pageCreate'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/delete/$',
        PageDeleteView.as_view(), name='pageDelete'),

    url(r'^sophenAdmin/event/list/$',
        EventListView.as_view(), name='eventList'),
    url(r'^sophenAdmin/event/create/$',
        EventCreateView.as_view(), name='eventCreate'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/$',
        EventDetailView.as_view(), name='eventDetail'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/update/$',
        EventUpdateView.as_view(), name='eventUpdate'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/delete/$',
        EventDeleteView.as_view(), name='eventDelete'),

    url(r'^sophenAdmin/file/list/$',
        FileListView.as_view(), name='fileList'),
    url(r'^sophenAdmin/file/create/$',
        FileCreateView.as_view(), name='fileCreate'),
    url(r'^sophenAdmin/file/(?P<pk>[\d]+)/update/$',
        FileUpdateView.as_view(), name='fileUpdate'),
    url(r'^sophenAdmin/file/(?P<pk>[\d]+)/delete/$',
        FileDeleteView.as_view(), name='fileDelete'),


    url(r'^sophenAdmin/gallery/list/$',
        GalleryListView.as_view(), name='galleryList'),
    url(r'^sophenAdmin/gallery/create/$',
        GalleryCreateView.as_view(), name='galleryCreate'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/$',
        GalleryDetailView.as_view(), name='galleryDetail'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/update/$',
        GalleryUpdateView.as_view(), name='galleryUpdate'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/delete/$',
        GalleryDeleteView.as_view(), name='galleryDelete'),

    url(r'^sophenAdmin/member/list/$',
        MemberListView.as_view(), name='memberList'),

    url(r'^sophenAdmin/menu/list/$',
        MenuListView.as_view(), name='menuList'),
    url(r'^sophenAdmin/menu/create/$',
        MenuCreateView.as_view(), name='menuCreate'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/$',
        MenuDetailView.as_view(), name='menuDetail'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/update/$',
        MenuUpdateView.as_view(), name='menuUpdate'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/delete/$',
        MenuDeleteView.as_view(), name='menuDelete'),


    url(r'^sophenAdmin/slider/list/$',
        SliderListView.as_view(), name='sliderList'),
    url(r'^sophenAdmin/slider/create/$',
        SliderCreateView.as_view(), name='sliderCreate'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/$',
        SliderDetailView.as_view(), name='sliderDetail'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/update/$',
        SliderUpdateView.as_view(), name='sliderUpdate'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/delete/$',
        SliderDeleteView.as_view(), name='sliderDelete'),

    url(r'^page/(?P<slug>[\w-]+)/$',
        FrontendPageDetailView.as_view(), name='frontendPageDetail'),
    url(r'^event/(?P<slug>[\w-]+)/$',
        FrontendEventDetailView.as_view(), name='frontendEventDetail'),
    url(r'^events/$',
        FrontendEventListView.as_view(), name='frontendEventList'),
    url(r'^gallery/$',
        FrontendGalleryListView.as_view(), name='frontendGalleryList'),
    url(r'^files/$',
        FrontendFileListView.as_view(), name='frontendFileList'),
    url(r'^membership/$',
        MembershipView.as_view(), name='membership'),
    
    url(r'^conference-membership/$',
        ConferenceMembershipView.as_view(), name='confmembership'),
    url(r'^contact/$',
        ContactView.as_view(), name='contact'),
    url(r'^members/$',
        CommitteeMember.as_view(), name='members'),
]

sohpen/templates/layouts/admin/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block head_title %}Admin Panel{% endblock %}</title>
    {% include "layouts/admin/include/head.html" %}
    {% block extra_head %}
    {% endblock %}

   
</head>
<body class="menubar-hoverable header-fixed full-content">
    <!-- BEGIN HEADER-->
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="#">
                                <span class="text-lg text-bold text-primary">ADMIN PANEL</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">
                <ul class="header-nav header-nav-options">
                    <li>
                        <!-- Search form -->
                        <form class="navbar-search" role="search">
                            <div class="form-group">
                                <input type="search" class="form-control" name="headerSearch" placeholder="Enter your keyword">
                            </div>
                            <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul><!--end .header-nav-options -->
                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <img src="{% static 'user.jpg' %}" alt="" />
                            <span class="profile-info">
                                {{request.user.get_full_name}}
                                <small> {{request.user.username}}</small>
                            </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li><a href="{% url 'website:changePassword' %}"><i class="fa fa-fw fa-asterisk"></i> Change Password</a></li>
                            <li><a href="#"  data-toggle="modal" data-target="#logOutModal"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <div class="modal fade" id="logOutModal" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Log Out</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'website:adminLogOut' %}"  style="text-decoration:none;">Logout</a></button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- END SIMPLE MODAL MARKUP -->


    <!-- BEGIN BASE-->
    <div id="base">
        {% if messages %}
        {% for message in messages %}
        <div id="toast-container" class="toast-bottom-right" aria-live="polite" role="alert">
           <div class="toast toast-{{message.tags}}">
               <div class="toast-message">{{ message }}</div>
           </div>
       </div>
       {% endfor %}
       {% endif %}
       <!-- BEGIN CONTENT-->
       <div id="content">
        {% block content %}
        {% endblock %}
    </div><!--end #content-->
    <!-- END CONTENT -->
    {% block menubar%}
    <!-- BEGIN MENUBAR-->
    <div id="menubar" class="menubar-inverse ">
        <div class="menubar-fixed-panel">
            <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="expanded">
                <a href="#">
                    <span class="text-lg text-bold text-primary ">SOPHEN&nbsp;ADMIN</span>
                </a>
            </div>
        </div>
        <div class="menubar-scroll-panel">

            <!-- BEGIN MAIN MENU -->
            <ul id="main-menu" class="gui-controls">

                <!-- BEGIN DASHBOARD -->
                <li id="dashboard">
                    <a href="{% url 'website:dashboard'%}">
                        <div class="gui-icon"><i class="fa fa-home"></i></div>
                        <span class="title">Dashboard</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->
                <li id="event">
                    <a href="{% url 'website:eventList'%}">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Event</span>
                    </a>
                </li><!--end /menu-li -->
                <li id="file">
                    <a href="{% url 'website:fileList'%}">
                        <div class="gui-icon"><i class="fa fa-file-pdf-o"></i></div>
                        <span class="title">File</span>
                    </a>
                </li><!--end /menu-li -->
                <li id="gallery">
                    <a href="{% url 'website:galleryList'%}">
                        <div class="gui-icon"><i class="fa fa-image"></i></div>
                        <span class="title">Gallery</span>
                    </a>
                </li><!--end /menu-li -->
                <li id="member">
                    <a href="{% url 'website:memberList'%}">
                        <div class="gui-icon"><i class="fa fa-users"></i></div>
                        <span class="title">Member</span>
                    </a>
                </li><!--end /menu-li -->
                 <li id="page">
                    <a href="{% url 'website:confList'%}">
                        <div class="gui-icon"><i class="fa fa-newspaper-o"></i></div>
                        <span class="title">Conference Entries</span>
                    </a>
                </li>
                <li id="menu">
                    <a href="{% url 'website:menuList'%}">
                        <div class="gui-icon"><i class="fa fa-server"></i></div>
                        <span class="title">Menu</span>
                    </a>
                </li><!--end /menu-li -->
                <li id="page">
                    <a href="{% url 'website:pageList'%}">
                        <div class="gui-icon"><i class="fa fa-newspaper-o"></i></div>
                        <span class="title">Page</span>
                    </a>
                </li><!--end /menu-li -->

                <li id="slider">
                    <a href="{% url 'website:sliderList'%}">
                        <div class="gui-icon"><i class="fa fa-photo"></i></div>
                        <span class="title">Slider</span>
                    </a>
                </li><!--end /menu-li -->



            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->

            <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                    <span class="opacity-75">Powered By</span> <strong>Prixa</strong>
                </small>
            </div>
        </div><!--end .menubar-scroll-panel-->
    </div><!--end #menubar-->
    <!-- END MENUBAR -->
    {% endblock menubar %}
    </div><!--end #base-->
<!-- END BASE -->

    {% include "layouts/admin/include/javascript.html" %}
    <script type="text/javascript">
        $(function(){
            {% if messages %}
            toastr.clear();
            {% for message in messages %}
            toastr.options.closeButton = true;
            toastr.options.progressBar = true;
            toastr.options.debug = false;
            toastr.options.positionClass = 'toast-bottom-right';
            toastr.options.showDuration = 333;
            toastr.options.hideDuration = 333;
            toastr.options.timeOut = 4000;
            toastr.options.extendedTimeOut = 4000;
            toastr.options.showEasing = 'swing';
            toastr.options.hideEasing = 'swing';
            toastr.options.showMethod = 'slideDown';
            toastr.options.hideMethod = 'slideUp';
            toastr.{{message.tags}}('{{message}}', '');
            {% endfor %}
            {% endif %}
        });

    </script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>