sohpen/sohpen/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls', namespace='website')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sohpen/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^testfront/$', TestFrontend.as_view(), name="test"),
    url(r'^$', HomeView.as_view(), name="home"),


    url(r'^sophenAdmin/$', Dashboard.as_view(), name="dashboard_main"),
    url(r'^sophenAdmin/dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^sophenAdmin/login/$', AdminLogInView.as_view(), name='adminLogIn'),
    url(r'^sophenAdmin/logout/$', AdminLogOutView.as_view(), name='adminLogOut'),
    url(r'^sophenAdmin/password-change/$',
        ChangePasswordView.as_view(), name='changePassword'),

    url(r'^sophenAdmin/page/list/$',
        PageListView.as_view(), name='pageList'),
    url(r'^sophenAdmin/conferenceMembership/list/$',
        ConferenceMemberListView.as_view(), name='confList'),
    url(r'^sophenAdmin/conferenceMembershipDetail/(?P<pk>[\d]+)$',
        ConferenceRegistrationDetailView.as_view(), name='confDetail'),
    url(r'^sophenAdmin/page/create/$',
        PageCreateView.as_view(), name='pageCreate'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^sophenAdmin/page/(?P<slug>[\w-]+)/delete/$',
        PageDeleteView.as_view(), name='pageDelete'),

    url(r'^sophenAdmin/event/list/$',
        EventListView.as_view(), name='eventList'),
    url(r'^sophenAdmin/event/create/$',
        EventCreateView.as_view(), name='eventCreate'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/$',
        EventDetailView.as_view(), name='eventDetail'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/update/$',
        EventUpdateView.as_view(), name='eventUpdate'),
    url(r'^sophenAdmin/event/(?P<slug>[\w-]+)/delete/$',
        EventDeleteView.as_view(), name='eventDelete'),

    url(r'^sophenAdmin/file/list/$',
        FileListView.as_view(), name='fileList'),
    url(r'^sophenAdmin/file/create/$',
        FileCreateView.as_view(), name='fileCreate'),
    url(r'^sophenAdmin/file/(?P<pk>[\d]+)/update/$',
        FileUpdateView.as_view(), name='fileUpdate'),
    url(r'^sophenAdmin/file/(?P<pk>[\d]+)/delete/$',
        FileDeleteView.as_view(), name='fileDelete'),


    url(r'^sophenAdmin/gallery/list/$',
        GalleryListView.as_view(), name='galleryList'),
    url(r'^sophenAdmin/gallery/create/$',
        GalleryCreateView.as_view(), name='galleryCreate'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/$',
        GalleryDetailView.as_view(), name='galleryDetail'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/update/$',
        GalleryUpdateView.as_view(), name='galleryUpdate'),
    url(r'^sophenAdmin/gallery/(?P<pk>[\d]+)/delete/$',
        GalleryDeleteView.as_view(), name='galleryDelete'),

    url(r'^sophenAdmin/member/list/$',
        MemberListView.as_view(), name='memberList'),

    url(r'^sophenAdmin/menu/list/$',
        MenuListView.as_view(), name='menuList'),
    url(r'^sophenAdmin/menu/create/$',
        MenuCreateView.as_view(), name='menuCreate'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/$',
        MenuDetailView.as_view(), name='menuDetail'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/update/$',
        MenuUpdateView.as_view(), name='menuUpdate'),
    url(r'^sophenAdmin/menu/(?P<pk>[\d]+)/delete/$',
        MenuDeleteView.as_view(), name='menuDelete'),


    url(r'^sophenAdmin/slider/list/$',
        SliderListView.as_view(), name='sliderList'),
    url(r'^sophenAdmin/slider/create/$',
        SliderCreateView.as_view(), name='sliderCreate'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/$',
        SliderDetailView.as_view(), name='sliderDetail'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/update/$',
        SliderUpdateView.as_view(), name='sliderUpdate'),
    url(r'^sophenAdmin/slider/(?P<pk>[\d]+)/delete/$',
        SliderDeleteView.as_view(), name='sliderDelete'),

    url(r'^page/(?P<slug>[\w-]+)/$',
        FrontendPageDetailView.as_view(), name='frontendPageDetail'),
    url(r'^event/(?P<slug>[\w-]+)/$',
        FrontendEventDetailView.as_view(), name='frontendEventDetail'),
    url(r'^events/$',
        FrontendEventListView.as_view(), name='frontendEventList'),
    url(r'^gallery/$',
        FrontendGalleryListView.as_view(), name='frontendGalleryList'),
    url(r'^files/$',
        FrontendFileListView.as_view(), name='frontendFileList'),
    url(r'^membership/$',
        MembershipView.as_view(), name='membership'),
    
    url(r'^conference-membership/$',
        ConferenceMembershipView.as_view(), name='confmembership'),
    url(r'^contact/$',
        ContactView.as_view(), name='contact'),
    url(r'^members/$',
        CommitteeMember.as_view(), name='members'),
]

sohpen/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView, View
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import *
from django.core.mail import send_mail
from django.shortcuts import HttpResponseRedirect, HttpResponse


class LoginMixin(LoginRequiredMixin):
    login_url = '/sophenAdmin/login/'
    redirect_field_name = 'redirect_to'


class HomeMixin(object):
    def get_context_data(self, **kwargs):
        context = super(HomeMixin, self).get_context_data(**kwargs)
        context['menu_root'] = Menu.get_root()
        context['latest_posts'] = Page.objects.filter(deleted_at=None).order_by('-created_at')[:3]
        
        return context


class Dashboard(LoginMixin, TemplateView):
    template_name = "dashboard.html"
    



class TestFrontend(HomeMixin, TemplateView):
    template_name = "testfront.html"


class ChangePasswordView(LoginMixin, View):
    def get(self, request):
        form = ChangePasswordForm()
        context = {
            'form': form,
        }
        return render(request, 'website/changePassword.html', context)

    def post(self, request):
        form = ChangePasswordForm(request.POST or None)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['confirm_password']
            user = authenticate(
                username=request.user.username, password=old_password)
            print(user, old_password, new_password)
            if user:
                user.set_password(new_password)
                user.save()
                login(request, user)
                messages.success(request, "Password Changed")
                return redirect('website:dashboard')

            else:
                messages.error(request, "Old Password Wrong")
                return redirect('website:changePassword')
        else:
            print(form.errors)

        context = {
            'form': form,
        }
        return render(request, 'website/changePassword.html', context)


class AdminLogInView(View):
    def get(self, request):
        form = LogInForm()
        context = {
            'form': form,
        }
        return render(request, 'website/adminLogIn.html', context)

    def post(self, request):
        form = LogInForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                messages.success(request, "Logged In Successfully")
                login(request, user)
                return redirect('website:dashboard')
        messages.warning(request, "Log In Failure")
        context = {
            'form': form,
        }
        return render(request, 'website/adminLogIn.html', context)


class AdminLogOutView(LoginMixin, View):
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(request)
        messages.success(request, "Logged Out Successfully")
        return redirect('website:adminLogIn')


class PageCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = Page
    template_name = 'website/pageCreate.html'
    form_class = PageForm
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Added"


class PageUpdateView(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Page
    template_name = 'website/pageUpdate.html'
    form_class = PageForm
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Updated"


class PageDeleteView(LoginMixin, SuccessMessageMixin, DeleteView):
    model = Page
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:pageList")
    success_message = "Page Successfully Deleted"


class PageDetailView(LoginMixin, DetailView):
    model = Page
    template_name = 'website/pageDetail.html'

class ConferenceRegistrationDetailView(LoginMixin, DetailView):
    model = ConferenceMember
    context_object_name = "member"
    template_name = 'website/conferenceMembershipDetail.html'

class PageListView(LoginMixin, ListView):
    model = Page
    template_name = 'website/pageList.html'
    context_object_name = 'pages'

    def get_queryset(self):
        return Page.objects.filter(deleted_at=None)


class EventCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = Event
    template_name = 'website/eventCreate.html'
    form_class = EventForm
    success_url = reverse_lazy("website:eventList")
    success_message = "Event Successfully Added"


class EventUpdateView(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Event
    template_name = 'website/eventUpdate.html'
    form_class = EventForm
    success_url = reverse_lazy("website:eventList")
    success_message = "Event Successfully Updated"


class EventDeleteView(LoginMixin, SuccessMessageMixin, DeleteView):
    model = Event
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:eventList")
    success_message = "Event Successfully Deleted"


class EventDetailView(LoginMixin, DetailView):
    model = Event
    template_name = 'website/eventDetail.html'


class EventListView(LoginMixin, ListView):
    model = Event
    template_name = 'website/eventList.html'
    context_object_name = 'events'

    def get_queryset(self):
        return Event.objects.filter(deleted_at=None)


class ConferenceMemberListView(LoginMixin, ListView):
    model = ConferenceMember
    template_name = 'website/conferenceMemberList.html'
    context_object_name = 'members'

    def get_queryset(self):
        return ConferenceMember.objects.filter(deleted_at=None)


class MenuCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = Menu
    template_name = 'website/menuCreate.html'
    form_class = MenuForm
    success_url = reverse_lazy("website:menuList")
    success_message = "Menu Successfully Added"


class MenuUpdateView(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Menu
    template_name = 'website/menuUpdate.html'
    form_class = MenuForm
    success_url = reverse_lazy("website:menuList")
    success_message = "Menu Successfully Updated"


class MenuDeleteView(LoginMixin, SuccessMessageMixin, DeleteView):
    model = Menu
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:menuList")
    success_message = "Menu Successfully Deleted"


class MenuDetailView(LoginMixin, DetailView):
    model = Menu
    template_name = 'website/menuDetail.html'


class MenuListView(LoginMixin, ListView):
    model = Menu
    template_name = 'website/menuList.html'
    context_object_name = 'menus'

    def get_queryset(self):
        return Menu.objects.filter(deleted_at=None)


class SliderCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = Slider
    template_name = 'website/sliderCreate.html'
    form_class = SliderForm
    success_url = reverse_lazy("website:sliderList")
    success_message = "slider Successfully Added"


class SliderUpdateView(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Slider
    template_name = 'website/sliderUpdate.html'
    form_class = SliderForm
    success_url = reverse_lazy("website:sliderList")
    success_message = "Slider Successfully Updated"


class SliderDeleteView(LoginMixin, SuccessMessageMixin, DeleteView):
    model = Slider
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:sliderList")
    success_message = "Slider Successfully Deleted"


class SliderDetailView(LoginMixin, DetailView):
    model = Slider
    template_name = 'website/sliderDetail.html'


class SliderListView(LoginMixin, ListView):
    model = Slider
    template_name = 'website/sliderList.html'
    context_object_name = 'photos'

    def get_queryset(self):
        return Slider.objects.filter(deleted_at=None)


class GalleryCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = Gallery
    template_name = 'website/galleryCreate.html'
    form_class = GalleryForm
    success_url = reverse_lazy("website:galleryList")
    success_message = "Gallery Successfully Added"


class GalleryDetailView(LoginMixin, DetailView):
    model = Gallery
    template_name = 'website/galleryDetail.html'


class GalleryListView(LoginMixin, ListView):
    model = Gallery
    template_name = 'website/galleryList.html'
    context_object_name = 'photos'

    def get_queryset(self):
        return Gallery.objects.filter(deleted_at=None)


class GalleryUpdateView(LoginMixin, SuccessMessageMixin, UpdateView):
    model = Gallery
    template_name = 'website/galleryUpdate.html'
    form_class = GalleryForm
    success_url = reverse_lazy("website:galleryList")
    success_message = "Gallery Successfully Updated"


class GalleryDeleteView(LoginMixin, SuccessMessageMixin, DeleteView):
    model = Gallery
    template_name = 'website/delete.html'
    success_url = reverse_lazy("website:galleryList")
    success_message = "Gallery Successfully Deleted"


class FileCreateView(LoginMixin, SuccessMessageMixin, CreateView):
    model = File
    template_name = 'website/fileCreate.html'
    form_class = FileForm
    success_url = reverse_lazy("website:fileList")
    success_message = "File Successfully Added"


class FileListView(LoginMixin, ListView):
    model = File
    template_name = 'website/fileList.html'
    context_object_name = 'files'

    def get_queryset(self):

sohpen/templates/website/changePassword.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}
{% block head_title %}
    {{block.super}} | Password Change
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
    <div class="card">
        <div class="card-body">
            <form action="." method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#password').addClass('active')
</script>
{% endblock %}

sohpen/templates/website/contact.html
{%extends 'layouts/frontend/base.html' %}
{% load staticfiles%}
{% block content %}
<!-- breadcrumbs -->
<div class="page-banner-area">
        <div class="container">
            <div class="col-md-4 col-md-offset-4">
                <div class="page-banner-content">
                    <div class="section-title">
                        <h2>Contact</h2>
                    </div>
                    <div class="other-page">
                        <ul>
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                              <li class="active"><a href="{% url 'website:contact' %}">Contact Us</a>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>



<div class="map-content-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="section-title">
                        <h2>SEND US A MESSAGE</h2>
                    </div>
                    <div class="section-content">
                        <p>To contact us, please fill in the form below.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
                    <div class="contact-page-form">
                        <form action="" method="POST">
                        {% csrf_token %}
                            <div class="col-md-12">
                                

                                    <div class="form-group">
                                            <label>Your name</label>
                                            {{form.name}}
                                        </div>
                                
                                <div class="form-group">
                                            <label>Your Subject</label>
                                            {{form.subject}}
                                        </div>
                                <div class="form-group">
                                            <label>Your Message</label>
                                            {{form.message}}
                                        </div>
                                        <div class="form-group">
                                           <input type="submit" value="Submit"/>
                                        </div>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="map-location-area">
        <div class="map-container">
            <div class="container">
                        <div class="map-caption">
                            <div class="section-title">
                                <h2>Contact Information</h2>
                            </div>
                            <div class="contact-list">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="icofont icofont-phone"></i>
                                            <span>Call : +977-1-4006650, 016208276</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont icofont-envelope"></i>
                                            <span>Email : info@sophen.org.np</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icofont icofont-location-pin "></i>
                                            <span>Panipokhari, Kathmandu Nepal</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                           
                        </div>
            </div>
            <div class="map-area">
                <div id="contactgoogleMap"></div>
            </div>
        </div>
    </div>
<!-- map -->

<!-- .map -->
<!-- .contact form & additional info -->
{% endblock content %}

sohpen/templates/website/galleryCreate.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}
{% block head_title %}
    {{block.super}} | Gallery Create
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#gallery').addClass('active')
</script>
{% endblock %}

sohpen/templates/website/menuList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Menu List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Menu List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;z-index:1000;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:menuCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:30px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Name</th>
                                    <th class="sort-alpha">URL</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for menu in menus %}
                                    <tr>
                                        <td class="sort-numeric">{{menu.id}}</td>
                                        <td><a href="{% url 'website:menuDetail' menu.id %}">{{menu.title}}</a></td>
                                        <td>{{menu.url}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:menuUpdate' menu.pk %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:menuDelete' menu.pk %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#menu').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

sohpen/templates/website/pageList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Page List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Page List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;z-index:1000;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:pageCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover"  style="margin-bottom:30px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Name</th>
                                    <th class="sort-alpha">Slug</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for page in pages %}
                                    <tr>
                                        <td class="sort-numeric">{{page.id}}</td>
                                        <td><a href="{% url 'website:pageDetail' page.slug %}">{{page.title}}</a></td>
                                        <td>{{page.slug}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:pageUpdate' page.slug %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:pageDelete' page.slug %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#page').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}